triggers:
  nameOverride: the-open-shifter
  apps:
  - name: fuse-quickstarts
    project: workflow-fuse
    enabled: true
    environments:
      - name: dev
        kind: ci
        volumeSize: 1Gi
        ref:
          value: develop
          kind: heads
        event: push
      - name: staging
        kind: cd
        ref:
          value: master
          kind: heads
        event: pull_request
      - name: prod
        kind: cd
        ref:
          value: ^v.+
          kind: tag
        event: push
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi
